export { default as Home } from '@/pages/Home.vue'
export { default as Login } from '@/pages/auth/Login.vue'
export { default as Registration } from '@/pages/auth/Registration.vue'
export { default as Predict } from '@pages/predict/Predict.vue'
export { default as Config } from '@/pages/config/Config.vue'
export { default as Settings } from '@pages/settings/Settings.vue'
