export { default as Home } from '@/pages/Home.vue'
export { default as Login } from '@/pages/auth/Login.vue'
export { default as Registration } from '@/pages/auth/Registration.vue'
export { default as Ai } from '@/pages/ai/Ai.vue'
export { default as Config } from '@/pages/config/Config.vue'